#define MCP_SUBSYSTEM_ACTION_ROUTING_DECLARATIONS \
MCP_DECLARE_ACTION_HANDLER(HandleExecuteEditorFunction); \
MCP_DECLARE_ACTION_HANDLER(HandleControlActorAction); \
MCP_DECLARE_ACTION_HANDLER(HandleControlEditorAction); \
MCP_DECLARE_ACTION_HANDLER(HandleLevelAction); \
MCP_DECLARE_ACTION_HANDLER(HandleUiAction); \
MCP_DECLARE_ACTION_HANDLER(HandleAnimationPhysicsAction); \
MCP_DECLARE_ACTION_HANDLER(HandleEffectAction); \
MCP_DECLARE_ACTION_HANDLER(HandleBlueprintAction); \
MCP_DECLARE_ACTION_HANDLER(HandleSequenceAction); \
MCP_DECLARE_ACTION_HANDLER(HandleInputAction);
