#define MCP_SUBSYSTEM_PROPERTY_COLLECTION_DECLARATIONS \
MCP_DECLARE_ACTION_HANDLER(HandleSetObjectProperty); \
MCP_DECLARE_ACTION_HANDLER(HandleGetObjectProperty); \
MCP_DECLARE_ACTION_HANDLER(HandleArrayAppend); \
MCP_DECLARE_ACTION_HANDLER(HandleArrayRemove); \
MCP_DECLARE_ACTION_HANDLER(HandleArrayInsert); \
MCP_DECLARE_ACTION_HANDLER(HandleArrayGetElement); \
MCP_DECLARE_ACTION_HANDLER(HandleArraySetElement); \
MCP_DECLARE_ACTION_HANDLER(HandleArrayClear); \
MCP_DECLARE_ACTION_HANDLER(HandleMapSetValue); \
MCP_DECLARE_ACTION_HANDLER(HandleMapGetValue); \
MCP_DECLARE_ACTION_HANDLER(HandleMapRemoveKey); \
MCP_DECLARE_ACTION_HANDLER(HandleMapHasKey); \
MCP_DECLARE_ACTION_HANDLER(HandleMapGetKeys); \
MCP_DECLARE_ACTION_HANDLER(HandleMapClear); \
MCP_DECLARE_ACTION_HANDLER(HandleSetAdd); \
MCP_DECLARE_ACTION_HANDLER(HandleSetRemove); \
MCP_DECLARE_ACTION_HANDLER(HandleSetContains); \
MCP_DECLARE_ACTION_HANDLER(HandleSetClear);
