#define MCP_SUBSYSTEM_ASSET_WORKFLOW_DECLARATIONS \
MCP_DECLARE_PAYLOAD_HANDLER(HandleImportAsset); \
MCP_DECLARE_PAYLOAD_HANDLER(HandleCreateMaterial); \
MCP_DECLARE_PAYLOAD_HANDLER(HandleCreateMaterialInstance); \
MCP_DECLARE_PAYLOAD_HANDLER(HandleDuplicateAsset); \
MCP_DECLARE_PAYLOAD_HANDLER(HandleRenameAsset); \
MCP_DECLARE_PAYLOAD_HANDLER(HandleMoveAsset); \
MCP_DECLARE_PAYLOAD_HANDLER(HandleDeleteAssets); \
MCP_DECLARE_PAYLOAD_HANDLER(HandleListAssets); \
MCP_DECLARE_PAYLOAD_HANDLER(HandleGetAsset); \
MCP_DECLARE_PAYLOAD_HANDLER(HandleCreateFolder); \
MCP_DECLARE_PAYLOAD_HANDLER(HandleGetDependencies); \
MCP_DECLARE_PAYLOAD_HANDLER(HandleGetAssetGraph); \
MCP_DECLARE_PAYLOAD_HANDLER(HandleSetTags); \
MCP_DECLARE_PAYLOAD_HANDLER(HandleSetMetadata); \
MCP_DECLARE_PAYLOAD_HANDLER(HandleGetMetadata); \
MCP_DECLARE_PAYLOAD_HANDLER(HandleGenerateReport); \
MCP_DECLARE_PAYLOAD_HANDLER(HandleValidateAsset); \
MCP_DECLARE_PAYLOAD_HANDLER(HandleAddMaterialParameter); \
MCP_DECLARE_PAYLOAD_HANDLER(HandleListMaterialInstances); \
MCP_DECLARE_PAYLOAD_HANDLER(HandleResetInstanceParameters); \
MCP_DECLARE_PAYLOAD_HANDLER(HandleDoesAssetExist); \
MCP_DECLARE_PAYLOAD_HANDLER(HandleGetMaterialStats); \
MCP_DECLARE_PAYLOAD_HANDLER(HandleRebuildMaterial);
