import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const out = path.join(root, "data", "expansion");
fs.mkdirSync(out, { recursive: true });
const write = (name, value) => fs.writeFileSync(path.join(out, name), JSON.stringify(value, null, 2) + "\n", "utf8");

const objects = [];
const addObject = (id, en, zh, typeEn, typeZh, brightness, light, clarity, stability, hintEn, hintZh, learnEn, learnZh, visual) => objects.push({
  id, name_en: en, name_zh: zh, type_en: typeEn, type_zh: typeZh, x: 512, y: 280,
  brightness, color: visual.color, difficulty: visual.difficulty ?? 5,
  required_light_score: light, required_clarity: clarity, required_stability: stability,
  short_hint_en: hintEn, short_hint_zh: hintZh, learning_text_en: learnEn, learning_text_zh: learnZh,
  naked_eye_visible: visual.nakedEye ?? false, apparent_magnitude: visual.magnitude ?? 5,
  sprite_path: visual.sprite, visual_profile: visual.profile
});

addObject("mercury", "Mercury", "水星", "Inner planet", "内行星", 68, 38, 62, 58, "A tiny gray disk close to the horizon.", "靠近地平线的微小灰色圆面。", "Mercury never strays far from the Sun, so low altitude and twilight turbulence are the real challenge.", "水星离太阳的角距始终不大，因此低高度和暮光大气扰动才是真正难点。", {sprite:"res://assets/telescope_view/expansion/mercury.svg",profile:"cratered_gray_disk",color:"gray",magnitude:-0.4,nakedEye:true});
addObject("venus", "Venus", "金星", "Inner planet", "内行星", 96, 30, 58, 48, "A brilliant white crescent that can easily overexpose.", "极亮、容易过曝的白色弯月形圆面。", "Venus shows phases. Lower power and controlled exposure preserve the crescent edge.", "金星具有月相；降低倍率并控制曝光才能保留弯月边缘。", {sprite:"res://assets/telescope_view/expansion/venus.svg",profile:"bright_crescent",color:"ivory",magnitude:-4.2,nakedEye:true});
addObject("saturn", "Saturn", "土星", "Ringed planet", "有环行星", 78, 48, 72, 74, "A pale disk crossed by a broad ring.", "被宽阔光环横穿的淡黄色圆面。", "Saturn's rings need steady air and a stable mount; excessive power magnifies turbulence instead of detail.", "土星环需要稳定大气和支架；过高倍率只会放大扰动，而不会增加细节。", {sprite:"res://assets/telescope_view/expansion/saturn.svg",profile:"ringed_planet",color:"pale gold",magnitude:0.6,nakedEye:true});
addObject("uranus", "Uranus", "天王星", "Ice giant", "冰巨星", 42, 62, 82, 72, "A very small blue-green disk, not a point star.", "很小的蓝绿色圆面，而不是恒星光点。", "Uranus is resolved only with high power and precise focus. Its color and disk separate it from field stars.", "天王星需要高倍率与精准调焦才能分辨圆面；颜色和圆面可把它与背景恒星区分开。", {sprite:"res://assets/telescope_view/expansion/uranus.svg",profile:"cyan_disk",color:"blue green",magnitude:5.7});
addObject("neptune", "Neptune", "海王星", "Ice giant", "冰巨星", 24, 84, 78, 78, "A faint deep-blue disk hidden among field stars.", "藏在背景恒星间的暗淡深蓝色圆面。", "Neptune rewards finder-scope star hopping, large aperture, careful focus, and a long steady look.", "海王星需要寻星镜跳星定位、大口径、细致调焦和长时间稳定观察。", {sprite:"res://assets/telescope_view/expansion/neptune.svg",profile:"dim_blue_disk",color:"deep blue",magnitude:7.8});

addObject("moon_crater_copernicus", "Copernicus Crater", "哥白尼环形山", "Lunar crater", "月球环形山", 90, 25, 70, 55, "A bright-rimmed crater with radial ejecta.", "具有明亮环壁和放射纹的环形山。", "High power reveals the terraced rim, but only when focus and seeing remain stable.", "高倍率能显示阶梯状环壁，但焦点和视宁度必须稳定。", {sprite:"res://assets/telescope_view/expansion/moon_crater.svg",profile:"lunar_crater",color:"gray"});
addObject("moon_mare_tranquillitatis", "Mare Tranquillitatis", "静海", "Lunar mare", "月海", 90, 25, 52, 45, "A broad, dark basalt plain.", "宽阔而暗色的玄武岩平原。", "Low power gives the context needed to compare a lunar mare with brighter highlands.", "低倍率提供整体背景，便于比较暗色月海与明亮高地。", {sprite:"res://assets/telescope_view/expansion/moon_mare.svg",profile:"lunar_mare",color:"charcoal"});
addObject("moon_terminator", "Lunar Terminator", "月球终结线", "Lunar light boundary", "月面明暗界线", 88, 25, 68, 52, "A sharp boundary where long shadows reveal relief.", "长阴影凸显地形的明暗分界线。", "Near the terminator, low sunlight makes crater walls and mountains appear three-dimensional.", "终结线附近太阳高度低，环形山壁和山脉会呈现立体阴影。", {sprite:"res://assets/telescope_view/expansion/moon_terminator.svg",profile:"lunar_terminator",color:"gray"});

addObject("albireo", "Albireo", "辇道增七", "Double star", "双星", 62, 42, 76, 64, "A gold and blue pair that separates at higher power.", "在较高倍率下分开的金色与蓝色双星。", "Double stars test angular resolution: low power blends the pair, high power separates their colors.", "双星检验角分辨率：低倍率下两星混合，高倍率下可分辨颜色。", {sprite:"res://assets/telescope_view/expansion/albireo.svg",profile:"double_star",color:"gold blue",magnitude:3.1,nakedEye:true});
addObject("pleiades", "Pleiades", "昴星团", "Open cluster", "疏散星团", 70, 52, 48, 45, "A loose blue cluster that needs a wide field.", "需要宽视野才能完整容纳的蓝色疏散星团。", "The Pleiades teach framing: too much power loses the cluster's overall shape.", "昴星团用于学习取景：倍率过高会失去星团的整体形状。", {sprite:"res://assets/telescope_view/expansion/pleiades.svg",profile:"open_cluster",color:"blue white",magnitude:1.6,nakedEye:true});
addObject("m13", "Hercules Globular Cluster", "武仙座球状星团 M13", "Globular cluster", "球状星团", 32, 76, 68, 70, "A dense grainy sphere that partly resolves into stars.", "边缘可分解为恒星的致密颗粒状球体。", "Aperture gathers enough light to resolve the halo while moderate power preserves brightness.", "口径收集足够光线以分解外晕，中等倍率则保留亮度。", {sprite:"res://assets/telescope_view/expansion/m13.svg",profile:"globular_cluster",color:"warm white",magnitude:5.8});
addObject("ring_nebula", "Ring Nebula", "环状星云 M57", "Planetary nebula", "行星状星云", 18, 82, 66, 64, "A tiny smoke ring strengthened by a nebula filter.", "使用星云滤镜后更明显的小型烟圈。", "A narrowband filter increases contrast, while dark adaptation and averted vision reveal the faint ring.", "窄带滤镜能提高对比度，暗适应和侧视法可显出微弱环状结构。", {sprite:"res://assets/telescope_view/expansion/ring_nebula.svg",profile:"ring_nebula",color:"teal",magnitude:8.8});
addObject("lagoon_nebula", "Lagoon Nebula", "礁湖星云 M8", "Emission nebula", "发射星云", 22, 86, 54, 58, "A broad mist crossed by a dark lane.", "被暗带横穿的宽广雾状星云。", "Low power, a wide field, a nebula filter, and dark adaptation preserve its extended shape.", "低倍率、宽视野、星云滤镜和暗适应能保留它的延展形状。", {sprite:"res://assets/telescope_view/expansion/lagoon_nebula.svg",profile:"emission_nebula",color:"rose teal",magnitude:6.0});
addObject("sombrero_galaxy", "Sombrero Galaxy", "草帽星系 M104", "Galaxy", "星系", 14, 90, 72, 72, "A thin glow split by a dark dust lane.", "被暗尘带分开的细长微光。", "Large aperture and averted vision reveal the bright nucleus and edge-on dust lane during a long observation.", "大口径和侧视法在长时间观察中显出亮核与侧向尘埃带。", {sprite:"res://assets/telescope_view/expansion/sombrero.svg",profile:"edge_on_galaxy",color:"warm white",magnitude:8.0});

const constellationSpecs = [
  ["ursa_major", "Big Dipper", "北斗七星", "spring", 15, 58, [[.12,.62],[.27,.52],[.42,.56],[.55,.46],[.68,.38],[.79,.28],[.9,.34]], [0,1,2,3,4,5,6], "Use the bowl's pointer stars to find Polaris.", "利用斗口两颗指极星寻找北极星。"],
  ["cassiopeia", "Cassiopeia", "仙后座", "autumn", 25, 66, [[.12,.52],[.3,.34],[.48,.58],[.68,.3],[.88,.5]], [0,1,2,3,4], "Recognize the W shape opposite the Big Dipper.", "辨认与北斗七星隔北极星相望的 W 形。"],
  ["cygnus", "Cygnus", "天鹅座", "summer", 205, 62, [[.5,.1],[.5,.28],[.5,.48],[.5,.7],[.5,.9],[.22,.47],[.78,.47]], [0,1,2,3,4,3,5,3,6], "Follow the Northern Cross through the Milky Way.", "沿银河辨认北十字。"],
  ["lyra", "Lyra", "天琴座", "summer", 245, 70, [[.2,.22],[.52,.34],[.72,.5],[.55,.76],[.3,.62]], [0,1,2,3,4,1], "Start at bright Vega, then trace the small parallelogram.", "从明亮织女星开始，再描出小平行四边形。"],
  ["aquila", "Aquila", "天鹰座", "summer", 185, 54, [[.12,.52],[.3,.48],[.48,.5],[.67,.35],[.86,.25],[.67,.66],[.86,.78]], [0,1,2,3,4,3,2,5,6], "Use Altair as the center of the Summer Triangle route.", "以牛郎星为夏季大三角导航中心。"],
  ["taurus", "Taurus", "金牛座", "winter", 105, 48, [[.15,.25],[.35,.43],[.5,.55],[.65,.42],[.86,.22],[.5,.55],[.72,.75]], [0,1,2,3,4,3,2,5,6], "Trace the V-shaped Hyades and then locate the Pleiades.", "描出毕宿星团的 V 形，再定位昴星团。"],
  ["scorpius", "Scorpius", "天蝎座", "summer", 175, 26, [[.14,.2],[.3,.28],[.42,.42],[.5,.57],[.58,.7],[.72,.8],[.88,.7]], [0,1,2,3,4,5,6], "Follow the curved tail from red Antares near the horizon.", "从低空红色心宿二沿弯曲蝎尾追踪。"],
  ["orion_constellation", "Orion", "猎户座", "winter", 135, 42, [[.2,.15],[.78,.18],[.35,.45],[.5,.48],[.65,.45],[.25,.82],[.76,.8]], [0,2,3,4,1,4,6,5,2], "Use the three belt stars to orient the hourglass.", "用腰带三星确定沙漏形方向。"],
  ["leo", "Leo", "狮子座", "spring", 225, 50, [[.18,.65],[.3,.45],[.42,.3],[.56,.38],[.5,.56],[.68,.65],[.88,.62]], [0,1,2,3,4,0,5,6], "Find the sickle first, then extend east along the body.", "先找到镰刀形，再向东延伸狮身。"]
];

const constellations = [];
for (const [id,en,zh,season,az,alt,points,order,tipEn,tipZh] of constellationSpecs) {
  constellations.push({id,name_en:en,name_zh:zh,visible_seasons:[season],azimuth:az,altitude:alt,stars:points.map((p,i)=>({id:`${id}_${i+1}`,x:p[0],y:p[1],magnitude:i===0?2:1})),connection_order:order,navigation_tip_en:tipEn,navigation_tip_zh:tipZh});
  addObject(id,en,zh,"Constellation","星座",58,1,1,1,tipEn,tipZh,`${en} is learned as a complete sky pattern and a navigation tool, not as one isolated star.`,`${zh}要作为完整天空图形和导航工具来学习，而不是一颗孤立恒星。`,{sprite:"",profile:"constellation",color:"white",nakedEye:true,magnitude:2});
}

const cards = [];
const addCard = (id,titleEn,titleZh,textEn,textZh) => cards.push({id,title_en:titleEn,title_zh:titleZh,image:"",text_en:textEn,text_zh:textZh});
addCard("mercury_twilight","Mercury at Twilight","暮光中的水星","Mercury stays close to the Sun. Observe during the brief twilight window, keep power moderate, and expect severe low-altitude turbulence.","水星总在太阳附近。应抓住短暂暮光窗口，使用适中倍率，并预期低空会有强烈大气扰动。");
addCard("venus_phase_exposure","Venus: Phase and Exposure","金星：月相与曝光","Venus is bright enough to wash out its own crescent. Reduce exposure and avoid unnecessary magnification before identifying the phase.","金星亮得足以淹没自身弯月轮廓。识别月相前应降低曝光，避免不必要的高倍率。");
addCard("saturn_rings_seeing","Saturn's Rings and Seeing","土星环与视宁度","Ring detail depends on steady air and mounting. Wait through poor moments instead of assuming more power always helps.","土星环细节取决于稳定大气和支架。应等待扰动减弱，而不是认为倍率越高越好。");
addCard("ice_giant_disks","Resolving the Ice Giants","分辨冰巨星圆面","Uranus requires precise high-power focus; Neptune adds finder navigation, aperture, and patient integration.","天王星需要精准高倍调焦；海王星还需要寻星定位、口径和耐心积累微光。");
addCard("lunar_feature_scale","Lunar Features at Two Scales","两种尺度下的月面","Low power explains where a feature lies; high power reveals crater walls and terminator relief. Compare rather than assuming one eyepiece is always best.","低倍率说明地貌位置，高倍率显示环壁和终结线起伏。要做比较，而不是认定一种目镜永远最好。");
addCard("double_cluster_framing","Resolution and Framing","分辨率与取景","Double stars benefit from higher power, while open clusters need low power and a wide field. Match scale to structure.","双星受益于高倍率，疏散星团则需要低倍率和宽视野。应让尺度匹配结构。");
addCard("faint_object_techniques","Faint-Object Techniques","暗弱天体观测技巧","Aperture gathers light; dark adaptation protects sensitivity; averted vision uses the retina away from its color-rich center; filters can raise nebular contrast.","口径负责集光；暗适应保护灵敏度；侧视法利用视网膜中心以外区域；滤镜可提高星云对比度。");
for (const [id,en,zh,,, ,,,tipEn,tipZh] of constellationSpecs) addCard(`constellation_${id}`,`${en}: Shape and Navigation`,`${zh}：形状与导航`,`${tipEn} Connect the key stars in order, then verify season, azimuth, and altitude.`,`${tipZh} 按顺序连接关键恒星，再核对季节、方位角与俯仰角。`);

const levels = [];
const stories = {};
const baseParts = ["tripod","mount","tube","objective","eyepiece","focus_knob"];
const baseIds = ["basic_tripod","stable_mount","starter_tube","objective_100mm","eyepiece_20mm","basic_focus_knob"];
let number = 92;
const telescopeLevel = (target, titleEn, titleZh, descEn, descZh, card, mechanics, env={}, steps=[], badge="") => {
  const n=number++;
  const requiredParts=[...baseParts], requiredIds=[...baseIds];
  if (mechanics.require_tracking) requiredIds[1]="tracking_mount";
  if (mechanics.require_finder) { requiredParts.push("finder_scope"); requiredIds.push("basic_finder_scope"); }
  levels.push({id:`level_${n}`,level_number:n,title_en:titleEn,title_zh:titleZh,description_en:descEn,description_zh:descZh,observation_mode:"telescope",equipment_stage:"refractor_advanced",telescope_family:"refractor",requires_telescope:true,requires_focus:true,target_object_id:target,required_parts:requiredParts,required_part_ids:requiredIds,assembly_order:requiredParts,required_assembly_score:65,minimum_success_quality:"Good",required_concept_card:card,observation_requirements:mechanics,environment:{seeing:"good",sky_brightness:"dark",cloud_cover:0,...env},mission_steps:steps,drift_enabled:Boolean(mechanics.require_tracking),hold_seconds:mechanics.hold_seconds??0,hold_strict:Boolean(mechanics.require_tracking),hint_text_en:descEn,hint_text_zh:descZh,success_text_en:`Logged ${titleEn} with the required observing technique.`,success_text_zh:`已使用指定观测技巧记录“${titleZh}”。`,reward_credits:180,unlock_parts:[],unlock_equipment_stage:"refractor_advanced",badge,chapter_id:"ch14_solar_system_and_deep_sky",lesson_thread:card,practice_step:1,variation:"expansion",teaching_steps:[{id:`l${n}_${card}`,card_id:card,trigger:"before_observation",mode:"brief",required_once:true}]});
  return n;
};
const pairStory = (n, en, zh) => stories[`level_${n}_before`] = [{speaker:"Maya",text_en:en,text_zh:zh},{speaker:"Maya",text_en:"This is not a name swap. Watch the image and use the control that answers this target's specific difficulty.",text_zh:"这不是换个名字的重复任务。观察图像，并使用真正针对该目标困难的控制。"}];

let n=telescopeLevel("mercury","Twilight Messenger","暮光信使","Catch Mercury above 10° altitude before the twilight window closes.","在暮光窗口结束前，于 10° 以上捕捉水星。","mercury_twilight",{altitude_min:10,altitude_max:24,magnification_max:90,seeing_patience:0.55},{seeing:"poor",twilight:true}); pairStory(n,"Mercury is not mainly difficult because it is small. We look through a long wedge of warm, moving air near the horizon.","水星的主要困难不只是小，而是我们要穿过地平线附近厚而温暖、持续流动的大气。");
telescopeLevel("mercury","Mercury's Best Window","水星最佳窗口","Use moderate power and wait for a steadier low-altitude moment.","使用适中倍率，等待低空大气短暂稳定。","mercury_twilight",{altitude_min:12,altitude_max:28,magnification_max:80,seeing_patience:0.7},{seeing:"poor",twilight:true});
n=telescopeLevel("venus","A Crescent Behind the Glare","强光中的弯月","Lower exposure until Venus's crescent edge is preserved.","降低曝光，直到金星弯月边缘得以保留。","venus_phase_exposure",{exposure_min:0.2,exposure_max:0.48,magnification_max:100},{seeing:"average"}); pairStory(n,"Venus is brighter than the detail we want. Tonight, controlling excess light matters more than collecting more.","金星本身比我们想看的细节更亮。今晚，控制过量光线比增加集光更重要。");
telescopeLevel("venus","Compare the Phase","比较金星月相","Confirm the same phase at low and high power without overexposing it.","在低倍与高倍下确认同一月相，同时避免过曝。","venus_phase_exposure",{exposure_min:0.18,exposure_max:0.5,require_magnification_comparison:true},{seeing:"good"},[{id:"venus_low",label_en:"Record crescent at low power",label_zh:"低倍率记录弯月",require_part_id:"eyepiece_20mm"},{id:"venus_high",label_en:"Check the limb at high power",label_zh:"高倍率检查边缘",require_part_id:"eyepiece_10mm"}]);
n=telescopeLevel("saturn","Rings in Restless Air","扰动大气中的土星环","Hold Saturn steady and wait until the ring gap stops boiling.","稳住土星，等待环缝不再抖动。","saturn_rings_seeing",{stability_min:70,magnification_min:65,magnification_max:130,seeing_patience:0.7},{seeing:"average"}); pairStory(n,"Saturn tempts us to add power. But ring structure appears only when the air and mount can support that power.","土星很容易让人一味增加倍率，但只有大气和支架支撑得住时，环结构才会出现。");
telescopeLevel("saturn","Cassini Patience","耐心寻找环缝","Use tracking near 1.0x and maintain a stable view of the ring structure.","把追踪调到接近 1.0x，并稳定保持土星环视野。","saturn_rings_seeing",{stability_min:74,magnification_min:75,magnification_max:125,require_tracking:true,tracking_min:0.9,tracking_max:1.1,hold_seconds:8},{seeing:"average"});
n=telescopeLevel("uranus","A Disk, Not a Star","圆面而非星点","Use high power and exact focus to resolve Uranus's blue-green disk.","用高倍率和精准调焦分辨天王星的蓝绿色圆面。","ice_giant_disks",{magnification_min:85,focus_multiplier:0.7,stability_min:68},{seeing:"good"}); pairStory(n,"Uranus does not reward a quick glance. The proof is a tiny disk that survives precise focus instead of collapsing into a star point.","天王星不适合匆匆一瞥。证据是精准合焦后仍保持的小圆面，而不是缩成恒星光点。");
telescopeLevel("uranus","Color and Diameter","颜色与直径","Compare Uranus with nearby field stars and keep its disk sharply focused.","把天王星与附近恒星比较，并保持圆面清晰合焦。","ice_giant_disks",{magnification_min:90,focus_multiplier:0.65,stability_min:72},{seeing:"average"});
n=telescopeLevel("neptune","Star Hop to Neptune","跳星寻找海王星","Use the finder, aperture, and a long steady hold to locate the dim blue disk.","使用寻星镜、大口径与长时间稳定保持，定位暗淡蓝色圆面。","ice_giant_disks",{magnification_min:70,light_min:80,require_finder:true,dark_adaptation_min:0.65,hold_seconds:10,require_tracking:true,tracking_min:0.85,tracking_max:1.15},{seeing:"good"}); pairStory(n,"For Neptune, aim is part of observation. The finder gets us to the right star field; aperture and time separate the planet from the stars.","观测海王星时，瞄准本身就是观测的一部分。寻星镜带我们到正确星场，口径和时间再把行星从恒星中分离出来。");
telescopeLevel("neptune","The Faint Blue World","暗蓝色世界","Confirm Neptune with precise focus, dark adaptation, and twelve seconds of tracking.","通过精准调焦、暗适应和十二秒追踪确认海王星。","ice_giant_disks",{magnification_min:80,light_min:84,dark_adaptation_min:0.8,require_averted_vision:true,hold_seconds:12,require_tracking:true,tracking_min:0.92,tracking_max:1.08},{seeing:"good"});

n=telescopeLevel("moon_mare_tranquillitatis","Map the Lunar Maria","绘制月海位置","Frame the whole Moon at low power and distinguish dark maria from bright highlands.","低倍率容纳整个月面，区分暗色月海与明亮高地。","lunar_feature_scale",{magnification_max:60},{seeing:"good"},[{id:"mare_low",label_en:"Frame the lunar maria at low power",label_zh:"低倍率取景月海",require_part_id:"eyepiece_20mm"}]); pairStory(n,"The Moon is no longer one target. Low power gives us geography before high power gives us detail.","月球不再只是一个目标。低倍率先给我们地理位置，高倍率再给细节。");
telescopeLevel("moon_crater_copernicus","Terraces of Copernicus","哥白尼环形山阶地","Switch to high power and focus on the crater rim and ejecta rays.","切换高倍率，对准环形山壁和放射纹。","lunar_feature_scale",{magnification_min:70,focus_multiplier:0.75},{seeing:"average"},[{id:"crater_high",label_en:"Resolve crater terraces at high power",label_zh:"高倍率分辨环壁阶地",require_part_id:"eyepiece_10mm"}]);
telescopeLevel("moon_terminator","Shadows at the Terminator","终结线阴影","Track the terminator and use moderate power to read relief from long shadows.","追踪终结线，用中等倍率从长阴影判断地形起伏。","lunar_feature_scale",{magnification_min:45,magnification_max:95,require_tracking:true,tracking_min:0.85,tracking_max:1.15,hold_seconds:7},{seeing:"average"});
telescopeLevel("moon_terminator","One Moon, Two Magnifications","同一月面，两种倍率","Compare wide context and high-power relief before logging the terminator.","记录终结线前，比较宽视野背景和高倍率地形。","lunar_feature_scale",{require_magnification_comparison:true},{seeing:"good"},[{id:"terminator_low",label_en:"Locate terminator at low power",label_zh:"低倍率定位终结线",require_part_id:"eyepiece_20mm"},{id:"terminator_high",label_en:"Inspect relief at high power",label_zh:"高倍率检查地形",require_part_id:"eyepiece_10mm"}],"Lunar Cartographer");

n=telescopeLevel("albireo","Two Colors, Two Stars","双色双星","Increase power until Albireo separates into gold and blue components.","提高倍率，直到辇道增七分解为金色与蓝色两颗星。","double_cluster_framing",{magnification_min:70,focus_multiplier:0.8},{seeing:"good"}); pairStory(n,"A double star asks whether the telescope can separate angles, not whether it can make one bright blob larger.","双星考验的是望远镜能否分开角距离，而不是把一个亮斑放得更大。");
telescopeLevel("albireo","Hold the Pair Apart","稳定分离双星","Keep the pair separated through average seeing without excessive power.","在一般视宁度下保持双星分离，同时避免倍率过高。","double_cluster_framing",{magnification_min:65,magnification_max:120,stability_min:68},{seeing:"average"});
telescopeLevel("pleiades","The Cluster Does Not Fit","装不下的星团","Choose low power so the Pleiades remain a complete pattern.","选择低倍率，让昴星团保持完整图形。","double_cluster_framing",{magnification_max:55},{seeing:"good"},[{id:"pleiades_wide",label_en:"Frame the whole cluster",label_zh:"完整取景星团",require_part_id:"eyepiece_20mm"}]);
telescopeLevel("m13","Resolve the Cluster Halo","分解球状星团外晕","Use aperture and moderate power to resolve M13's grainy outer halo.","使用大口径和中等倍率分解 M13 的颗粒状外晕。","double_cluster_framing",{light_min:72,magnification_min:45,magnification_max:95,dark_adaptation_min:0.55},{seeing:"good"});
n=telescopeLevel("ring_nebula","A Ring in the Dark","黑暗中的星云环","Dark-adapt, enable the nebula filter, and use averted vision on M57.","完成暗适应，启用星云滤镜，并对 M57 使用侧视法。","faint_object_techniques",{filter:"nebula",dark_adaptation_min:0.8,require_averted_vision:true,light_min:78},{seeing:"good"}); pairStory(n,"A filter cannot create light, but it can reject the background wavelengths that hide a nebula. Your eyes still need time.","滤镜不能创造光，但能压低遮蔽星云的背景波段。你的眼睛仍然需要时间适应。");
telescopeLevel("ring_nebula","Direct vs Averted Vision","直视与侧视","Compare direct vision with averted vision while keeping the nebula filter active.","保持星云滤镜启用，比较直视与侧视效果。","faint_object_techniques",{filter:"nebula",dark_adaptation_min:0.9,require_averted_vision:true,hold_seconds:8},{seeing:"good"});
telescopeLevel("lagoon_nebula","Keep the Lagoon Wide","保留礁湖全貌","Use low power, a wide field, and a nebula filter for the extended cloud.","用低倍率、宽视野和星云滤镜观察延展云气。","faint_object_techniques",{filter:"nebula",magnification_max:60,dark_adaptation_min:0.75,light_min:80},{seeing:"good"});
telescopeLevel("sombrero_galaxy","The Dust Lane Appears","显现尘埃带","Use maximum aperture, averted vision, and a long tracked observation.","使用最大口径、侧视法和长时间追踪观测。","faint_object_techniques",{filter:"none",light_min:86,dark_adaptation_min:0.9,require_averted_vision:true,require_tracking:true,tracking_min:0.94,tracking_max:1.06,hold_seconds:12},{seeing:"good"},[],"Deep Sky Observer");

for (const [id,en,zh,season] of constellationSpecs) {
  const first=number++;
  const make=(num,titleSuffixEn,titleSuffixZh,practice)=>({id:`level_${num}`,level_number:num,title_en:`${en}: ${titleSuffixEn}`,title_zh:`${zh}：${titleSuffixZh}`,description_en:`Recognize ${en}, connect its key stars in order, and use the pattern to navigate.`,description_zh:`识别${zh}整体形状，按顺序连接关键恒星，并用图形导航。`,observation_mode:"constellation",equipment_stage:"eye",telescope_family:"none",requires_telescope:false,requires_focus:false,target_object_id:id,required_parts:[],required_part_ids:[],required_assembly_score:0,minimum_success_quality:"Good",required_concept_card:`constellation_${id}`,environment:{season,seeing:"good",sky_brightness:"dark"},hint_text_en:`Use the whole ${en} pattern, then center its catalog azimuth and altitude.`,hint_text_zh:`使用${zh}整体图形，再把星表方位角和高度角移到中心。`,success_text_en:`${en} shape, sequence, season, and position recorded.`,success_text_zh:`已记录${zh}的形状、顺序、季节与位置。`,reward_credits:150,unlock_parts:[],unlock_equipment_stage:"eye",badge:practice===2?"Constellation Navigator":"",chapter_id:"ch15_constellation_navigation",lesson_thread:`constellation_${id}`,practice_step:practice,variation:"expansion",teaching_steps:practice===1?[{id:`l${num}_constellation_${id}`,card_id:`constellation_${id}`,trigger:"before_observation",mode:"brief",required_once:true}]:[],drift_enabled:false,hold_seconds:0});
  levels.push(make(first,"Recognize the Pattern","识别图形",1));
  levels.push(make(number++,"Navigate by the Pattern","使用图形导航",2));
  pairStory(first,`We already know individual stars. Now ${en} turns several stars into a map: shape first, sequence second, position last.`, `我们已经认识单颗恒星。现在${zh}把多颗星变成地图：先看形状，再按顺序连线，最后核对位置。`);
}

const catalog = objects.filter(o=>o.visual_profile!=="constellation").map((o,i)=>({id:o.id,fallback_altitude:12+(i*7)%68,fallback_azimuth:(35+i*31)%360,naked_eye_visible:o.naked_eye_visible,apparent_magnitude:o.apparent_magnitude}));
write("celestial_objects.json", objects);
write("celestial_catalog.json", catalog);
write("constellations.json", constellations);
write("learning_cards.json", cards);
write("story_dialogues.json", stories);
write("levels.json", levels);
const artDir = path.join(root, "assets", "telescope_view", "expansion");
fs.mkdirSync(artDir, { recursive: true });
const svg = (body) => `<svg xmlns="http://www.w3.org/2000/svg" width="320" height="320" viewBox="0 0 320 320"><defs><filter id="g"><feGaussianBlur stdDeviation="5"/></filter></defs>${body}</svg>`;
const art = {
  mercury: `<circle cx="160" cy="160" r="72" fill="#aaa59a"/><circle cx="132" cy="126" r="17" fill="#77756f"/><circle cx="184" cy="181" r="23" fill="#85817a"/><circle cx="195" cy="119" r="11" fill="#d1cab9"/><path d="M105 196 Q160 230 213 187" fill="none" stroke="#696761" stroke-width="8"/>`,
  venus: `<circle cx="160" cy="160" r="78" fill="#fff4c7"/><circle cx="191" cy="147" r="84" fill="#060912"/><circle cx="150" cy="152" r="88" fill="#fff0ad" opacity=".22" filter="url(#g)"/>`,
  saturn: `<ellipse cx="160" cy="160" rx="132" ry="39" fill="none" stroke="#c8a56a" stroke-width="18"/><ellipse cx="160" cy="160" rx="67" ry="58" fill="#d9bd7e"/><path d="M97 151 H223M103 176 H217" stroke="#9b7043" stroke-width="8"/><path d="M38 160 Q160 203 282 160" fill="none" stroke="#f0d596" stroke-width="8"/>`,
  uranus: `<circle cx="160" cy="160" r="59" fill="#79d4cb"/><circle cx="145" cy="142" r="48" fill="#b2eee0" opacity=".28"/><circle cx="160" cy="160" r="65" fill="none" stroke="#82e3dc" stroke-width="5" opacity=".35"/>`,
  neptune: `<circle cx="160" cy="160" r="50" fill="#315ec9"/><path d="M115 145 Q160 128 205 145" fill="none" stroke="#6c91ed" stroke-width="8" opacity=".65"/><circle cx="147" cy="145" r="39" fill="#547be0" opacity=".2"/>`,
  moon_crater: `<circle cx="160" cy="160" r="112" fill="#aaa99d"/><circle cx="160" cy="160" r="57" fill="#575a58" stroke="#e1dcc8" stroke-width="14"/><circle cx="148" cy="150" r="24" fill="#747875"/><g stroke="#d8d1b9" stroke-width="5"><path d="M160 40V94M160 226V282M40 160H94M226 160H282M75 75L118 118M202 202L248 248"/></g>`,
  moon_mare: `<circle cx="160" cy="160" r="112" fill="#b8b6aa"/><path d="M68 130 Q105 75 151 110T239 112 Q264 165 225 210T139 230Q87 209 68 130" fill="#555b5c"/><circle cx="108" cy="85" r="22" fill="#d7d3c2"/>`,
  moon_terminator: `<circle cx="160" cy="160" r="112" fill="#d4cfb9"/><path d="M160 48 C105 92 205 126 151 160 C95 196 201 226 160 272 A112 112 0 0 1 160 48" fill="#15181c"/><g fill="#5f625f"><circle cx="147" cy="118" r="15"/><circle cx="170" cy="190" r="22"/><circle cx="145" cy="228" r="10"/></g>`,
  albireo: `<circle cx="122" cy="160" r="23" fill="#ffc35a"/><circle cx="122" cy="160" r="40" fill="#ffb43f" opacity=".18" filter="url(#g)"/><circle cx="205" cy="155" r="16" fill="#7db7ff"/><circle cx="205" cy="155" r="34" fill="#5598ff" opacity=".2" filter="url(#g)"/>`,
  pleiades: `<g fill="#b8d7ff">${[[80,90,7],[132,64,11],[184,102,8],[230,73,6],[102,174,9],[166,158,7],[218,194,10],[142,235,5]].map(([x,y,r])=>`<circle cx="${x}" cy="${y}" r="${r}"/><circle cx="${x}" cy="${y}" r="${r*2.7}" opacity=".12" filter="url(#g)"/>`).join("")}</g>`,
  m13: `<circle cx="160" cy="160" r="105" fill="#e8d6a8" opacity=".1" filter="url(#g)"/><g fill="#f4e6bf">${Array.from({length:70},(_,i)=>{const a=i*2.399,r=8+92*((i%17)/17);return `<circle cx="${160+Math.cos(a)*r}" cy="${160+Math.sin(a)*r}" r="${1+(i%4)}"/>`}).join("")}</g>`,
  ring_nebula: `<ellipse cx="160" cy="160" rx="88" ry="70" fill="none" stroke="#45d0b8" stroke-width="30" opacity=".7"/><ellipse cx="160" cy="160" rx="103" ry="84" fill="none" stroke="#7d4ea6" stroke-width="18" opacity=".3" filter="url(#g)"/>`,
  lagoon_nebula: `<path d="M38 184 Q78 72 153 119 Q217 60 284 154 Q227 245 151 213 Q88 260 38 184" fill="#ba5a87" opacity=".48" filter="url(#g)"/><path d="M66 172 Q133 132 258 165" fill="none" stroke="#10141e" stroke-width="25"/><g fill="#eaf2ff"><circle cx="101" cy="136" r="4"/><circle cx="206" cy="116" r="5"/><circle cx="239" cy="198" r="3"/></g>`,
  sombrero: `<ellipse cx="160" cy="160" rx="122" ry="42" fill="#dfcda7" opacity=".6" filter="url(#g)"/><ellipse cx="160" cy="160" rx="112" ry="18" fill="#efe2bf"/><path d="M52 160 Q160 143 268 160 Q160 178 52 160" fill="#11131a"/><circle cx="160" cy="155" r="19" fill="#fff2c8"/>`
};
for (const [name, body] of Object.entries(art)) fs.writeFileSync(path.join(artDir, `${name}.svg`), svg(body), "utf8");
const mechanicSummary = (req={}) => Object.entries(req).map(([k,v])=>`${k}=${v}`).join(", ") || "shape/order/season/Az-Alt navigation";
const rows = levels.map(l=>`| ${l.level_number} | ${l.title_en}<br>${l.title_zh} | ${l.target_object_id} | ${l.observation_mode === "constellation" ? "Naked-eye constellation deck" : l.required_part_ids.join(", ")} | ${mechanicSummary(l.observation_requirements)} | ${l.required_concept_card} | ${stories[`level_${l.level_number}_before`] ? "Maya introduction" : "guided practice / 复练"} |`).join("\n");
const doc = `# Observation Expansion (L92-L131)\n\nThis expansion is loaded from \`data/expansion/\`; legacy L1-L91 data is not rewritten. Mission completion continues through the existing Club Logbook pipeline.\n\n## Level Catalog\n\n| Level | Mission | Target | Equipment | Real mechanic / failure gates | Teaching | Story |\n|---:|---|---|---|---|---|---|\n${rows}\n\n## New Objects\n\n${objects.map(o=>`- **${o.name_en} / ${o.name_zh}** (\`${o.id}\`): ${o.learning_text_en} / ${o.learning_text_zh}`).join("\n")}\n\n## Constellation Interaction\n\nEvery constellation mission requires four verified stages: identify the complete silhouette, click key stars in the configured order, navigate to the catalog Az/Alt using A/D/W/S, and satisfy the configured seasonal visibility before recording the observation.\n\n## Visual Assets\n\nImplemented distinct in-game vector studies: ${Object.keys(art).map(n=>`\`${n}.svg\``).join(", ")}. They are transparent and remain sharp at the compressed gameplay scale.\n\n### Art still worth replacing with final painted assets\n\n- Mercury surface and twilight atmospheric dispersion states.\n- Venus phase variants (crescent, quarter, gibbous) and exposure-specific bloom masks.\n- Saturn ring tilt and Cassini Division variants.\n- Uranus and Neptune subtle banding at multiple seeing states.\n- Copernicus, Mare Tranquillitatis, and terminator photo-grade crops.\n- Albireo, Pleiades, M13, M57, M8, and M104 clear/dim/defocused raster triplets.\n- Optional constellation line-art plates; current star geometry is generated dynamically and already playable.\n`;
fs.writeFileSync(path.join(root, "docs", "OBSERVATION_EXPANSION.md"), doc, "utf8");
console.log(`Generated ${levels.length} levels, ${objects.length} objects, ${cards.length} cards, and ${constellations.length} constellations.`);
